{
 "title": "DevOps Portfolio Website Monitoring",
 "tags": [
  "task",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Node Exporter Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[5m])) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"node-exporter\"} / node_memory_MemTotal_bytes{job=\"node-exporter\"}))"
    }
   ]
  },
  {
   "title": "Portfolio Website Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-portfolio\"}"
    }
   ]
  },
  {
   "title": "Website Response Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox-portfolio\"}"
    }
   ]
  }
 ]
}